### ISSUE TITLE
More than one shelly instance for metering (multiple inverters)

### ISSUE THREAD

**Issue by hoschult** [vikt0rm/dbus-shelly-1pm-pvinverter#16]
Hi, wanted to ask if it is possible to use more than one shelly 1pm for metering different inverters with this plugin?

**Comment by pau1phi11ips** [comment]
See here: **https://community.victronenergy.com/questions/127339/shelly-1pm-as-pv-inverter-in-venusos.html?childToView=128106#comment-128106**

**Comment by vikt0rm** [comment]
Thanks @pau1phi11ips for the response. The question is answered from my perspective and can be closed.
