### ISSUE TITLE
PV-inverter is removed after restart

### ISSUE THREAD

**Issue by e-i-k-e** [vikt0rm/dbus-shelly-1pm-pvinverter#2]
Hello, 
after a restart the PV inverter kept disappearing. 
What can I do?

**Comment by vikt0rm** [comment]
On first try I would check the log for errors. And maybe restart the service.

**Comment by e-i-k-e** [comment]
The entry /data/dbus-shelly-1pm-pvinverter/install.sh in the rc.local seems to be removed after a restart. The file has the permissions 777
