### ISSUE TITLE
Bring Inverter to critical loads

### ISSUE THREAD

**Issue by miktin** [vikt0rm/dbus-shelly-1pm-pvinverter#3]
Hallo @vikt0rm
Is their a chance to bring Shelly 1pm to the critical loads?
PV-Wechselrichter is the Shelly, PV-Ladegerät is a Victron mppt.

Thanks
![Remote Console on LAN](https://user-images.githubusercontent.com/76965226/171721571-9be79058-362e-4db8-81b0-2a0aed73ac78.png)

**Comment by miktin** [comment]
Ok 
I give answer by  myself.
In dbus-Shelly-1pm-pvinverter.py  you have to change „Position“ Form 0 to 1.
I only have 3 Phases now on „Kritsche Lasten“
![Bildschirmfoto 2022-06-03 um 07 18 54](https://user-images.githubusercontent.com/76965226/171791602-4622786e-8407-4fe9-8f9d-04aa5b86628b.png)

**Comment by hoschult** [comment]
thx for sharing - I had the same requirement at my installation!

**Comment by ramack** [comment]
#18 would be a PR to make the position configurable

**Comment by vikt0rm** [comment]
Thanks to @ramack this PR is merged and fixed.
