### ISSUE TITLE
how can this be adopted for shelly-3em?

### ISSUE THREAD

**Issue by iz3man** [vikt0rm/dbus-shelly-1pm-pvinverter#6]
My huawei 2000L inverter is a three phase device which is monitored my a Shelly 3EM.

How can this script be adopted to 3-phases. As it seems this is based on a 3-phase script anyway, so it should be doable?

Thanks

**Comment by pau1phi11ips** [comment]
@iz3man see https://github.com/fabian-lauer/dbus-shelly-3em-smartmeter

**Comment by iz3man** [comment]
I know that, and it's in use, but this is for a GRIDMETER?! I want it to show as SOLAR INVERTER. If I just start another instance it will show up as energy meter.

**Comment by pau1phi11ips** [comment]
I think you need add `self._dbusservice.add_path('/Role', 'pvinverter')`

**Comment by iz3man** [comment]
Thanks. That was one of the things. Needed to change device_id and some other things as well. But it was like 5 changes only, and it seems to work now :)

**Comment by pau1phi11ips** [comment]
This can be closed I think @vikt0rm
